### ISSUE TITLE
Copy for ad - headline @compzilla

### ISSUE THREAD

**Issue by compzilla** [mozilla-rally/rally#464] opened 2022-11-04 01:08 UTC
https://docs.google.com/spreadsheets/d/1jjlf0hezu5bhTm24GzCXWLWbK25Ogzoq6wUaQysyuJU/edit#gid=0

**Comment by marniepw** [comment] 2022-12-08 01:09
Closing, duplicate of #547

**Closed by marniepw** 2022-12-08 01:09 UTC
