### ISSUE TITLE
Copy for landing page @KennedyM-zillian

### ISSUE THREAD

**Issue by compzilla** [mozilla-rally/rally#461] opened 2022-11-04 01:07 UTC
https://docs.google.com/document/d/1tMR-GlBn6atCyewATtIJKXbWpwV9_lWt8ahdXYY5Q-4/edit#

**Comment by KennedyM-zillian** [comment] 2022-11-07 16:52
What is this landing page?

**Comment by compzilla** [comment] 2022-11-07 17:36
We are going to test an editorial type ad on Pocket that will have it's own landing page. We are re-publishing the Hey Jane article, and we will need language before/after the article encouraging people to join Rally.

**Comment by marniepw** [comment] 2022-12-05 23:03
Copy doc: https://docs.google.com/document/d/1tMR-GlBn6atCyewATtIJKXbWpwV9_lWt8ahdXYY5Q-4/edit#

**Comment by marniepw** [comment] 2022-12-08 01:12
Closing, duplicate of #553  (I think)

**Closed by marniepw** 2022-12-08 01:12 UTC
